<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="AUL-DEV-03" name="testsuite.baseTest" tests="8" failures="0" timestamp="2022-04-22T00:15:50 PDT" time="0.759" errors="1">
  <testcase name="afterTestMethod" time="0.001" classname="testsuite.baseTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at utils.baseClass.afterTestMethod(baseClass.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.afterRun(TestRunner.java:877)
at org.testng.TestRunner.run(TestRunner.java:599)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- afterTestMethod -->
  <system-out/>
  <testcase name="VerifyeClaimsPortalforRepairFacilitieslink_27228_27231_27261" time="0.180" classname="testsuite.baseTest"/>
  <system-out/>
  <testcase name="VerifyRememberMyPasswordLocation_27214" time="0.218" classname="testsuite.baseTest"/>
  <system-out/>
  <testcase name="VerifyLocationPrivacyPolicyLink_27224_27239_27254" time="0.084" classname="testsuite.baseTest"/>
  <system-out/>
  <testcase name="VerifyWelcomeTextOnTheADLUILoginPage_27248_27244_27110" time="0.092" classname="testsuite.baseTest"/>
  <system-out/>
  <testcase name="VerifyGAPPortallinkfunctionality_27233_27259_27229" time="0.071" classname="testsuite.baseTest"/>
  <system-out/>
  <testcase name="VerifyForgotPassword_Loginastext_27238_27254_27220_27255_27237_27166" time="0.076" classname="testsuite.baseTest"/>
  <system-out/>
  <testcase name="Verify_image_on_the_right_side_of_the_login_page_27225" time="0.037" classname="testsuite.baseTest"/>
  <system-out/>
</testsuite> <!-- testsuite.baseTest -->
